# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'Example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Example
  pod 'DGSwitch', :path => '../'
end
